// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';

export function EjectDrive(arg1:string):Promise<void>;

export function GetCurrentJobs(arg1:string):Promise<config.JobsConfig>;

export function GetDrives():Promise<Array<string>>;

export function OpenFile():Promise<string>;

export function RunRipper(arg1:string):Promise<void>;
