// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EjectDrive(arg1) {
  return window['go']['main']['App']['EjectDrive'](arg1);
}

export function GetCurrentJobs(arg1) {
  return window['go']['main']['App']['GetCurrentJobs'](arg1);
}

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RunRipper(arg1) {
  return window['go']['main']['App']['RunRipper'](arg1);
}
